import { count } from "drizzle-orm";
import { db } from "./index";
import { catalogItems, trails, userGear } from "./schema";

const trailSeed = [
  {
    name: "John Muir Trail",
    region: "Sierra Nevada, CA",
    distanceMiles: 211,
    elevationGainFt: 47000,
    difficulty: "expert" as const,
    climate: "alpine" as const,
    seasonHint: "Jul–Sep",
    notes: "High elevation, cold nights, bear canisters required.",
  },
  {
    name: "Appalachian Trail (Smokies)",
    region: "Great Smoky Mountains",
    distanceMiles: 72,
    elevationGainFt: 18000,
    difficulty: "hard" as const,
    climate: "forest" as const,
    seasonHint: "Apr–Oct",
    notes: "Humid forest, frequent rain, shelter network available.",
  },
  {
    name: "Wonderland Trail",
    region: "Mount Rainier, WA",
    distanceMiles: 93,
    elevationGainFt: 22000,
    difficulty: "hard" as const,
    climate: "alpine" as const,
    seasonHint: "Jul–Sep",
    notes: "Volcanic alpine, snowfields early season, variable weather.",
  },
  {
    name: "Zion Narrows",
    region: "Zion NP, UT",
    distanceMiles: 16,
    elevationGainFt: 1500,
    difficulty: "moderate" as const,
    climate: "desert" as const,
    seasonHint: "Jun–Oct",
    notes: "Canyon water hiking, flash flood risk, warm days.",
  },
  {
    name: "Lost Coast Trail",
    region: "Northern California",
    distanceMiles: 25,
    elevationGainFt: 4000,
    difficulty: "moderate" as const,
    climate: "coastal" as const,
    seasonHint: "May–Oct",
    notes: "Tide tables critical, wind, salt spray, soft sand.",
  },
  {
    name: "Presidential Traverse",
    region: "White Mountains, NH",
    distanceMiles: 20,
    elevationGainFt: 8500,
    difficulty: "expert" as const,
    climate: "alpine" as const,
    seasonHint: "Jun–Sep",
    notes: "Exposed ridgeline, severe weather common above treeline.",
  },
];

const catalogSeed = [
  {
    name: "X-Mid 1",
    brand: "Durston",
    category: "shelter" as const,
    weightGrams: 765,
    priceUsd: 259,
    waterproofRating: "silnylon",
    durability: 8,
    comfort: 8,
    skillLevel: "intermediate" as const,
    bestFor: "alpine,forest,mixed",
    description: "Trekking-pole pyramid with excellent storm worthiness and living space.",
    imageHint: "tent",
  },
  {
    name: "Copper Spur HV UL2",
    brand: "Big Agnes",
    category: "shelter" as const,
    weightGrams: 1247,
    priceUsd: 550,
    waterproofRating: "silnylon",
    durability: 7,
    comfort: 9,
    skillLevel: "beginner" as const,
    bestFor: "forest,mixed,coastal",
    description: "Freestanding two-person tent with generous vestibules and easy pitch.",
    imageHint: "tent",
  },
  {
    name: "Notch Li",
    brand: "Six Moon Designs",
    category: "shelter" as const,
    weightGrams: 482,
    priceUsd: 515,
    waterproofRating: "Dyneema",
    durability: 6,
    comfort: 7,
    skillLevel: "advanced" as const,
    bestFor: "alpine,mixed",
    description: "Ultralight dual-trekking-pole shelter for weight-obsessed hikers.",
    imageHint: "tent",
  },
  {
    name: "NeoAir XLite NXT",
    brand: "Therm-a-Rest",
    category: "sleep" as const,
    weightGrams: 371,
    priceUsd: 210,
    rValue: 4.5,
    durability: 7,
    comfort: 8,
    skillLevel: "beginner" as const,
    bestFor: "alpine,forest,mixed,desert",
    description: "Industry-standard insulated pad with strong warmth-to-weight ratio.",
    imageHint: "sleeping-pad",
  },
  {
    name: "Tensor Extreme Conditions",
    brand: "NEMO",
    category: "sleep" as const,
    weightGrams: 525,
    priceUsd: 250,
    rValue: 8.5,
    durability: 8,
    comfort: 9,
    skillLevel: "intermediate" as const,
    bestFor: "alpine",
    description: "Winter-capable pad for cold alpine nights and shoulder seasons.",
    imageHint: "sleeping-pad",
  },
  {
    name: "Western Mountaineering UltraLite",
    brand: "Western Mountaineering",
    category: "sleep" as const,
    weightGrams: 822,
    priceUsd: 505,
    temperatureRatingF: 20,
    durability: 9,
    comfort: 9,
    skillLevel: "intermediate" as const,
    bestFor: "alpine,forest",
    description: "Premium down bag with excellent loft retention and longevity.",
    imageHint: "sleeping-bag",
  },
  {
    name: "Katabatic Flex 22",
    brand: "Katabatic",
    category: "sleep" as const,
    weightGrams: 595,
    priceUsd: 390,
    temperatureRatingF: 22,
    durability: 8,
    comfort: 8,
    skillLevel: "advanced" as const,
    bestFor: "alpine,mixed",
    description: "Quilt system that saves weight without sacrificing shoulder-season warmth.",
    imageHint: "quilt",
  },
  {
    name: "Exos 48",
    brand: "Osprey",
    category: "pack" as const,
    weightGrams: 1190,
    priceUsd: 240,
    capacityLiters: 48,
    durability: 8,
    comfort: 9,
    skillLevel: "beginner" as const,
    bestFor: "forest,mixed,coastal",
    description: "Ventilated frame pack that carries comfortably on longer approaches.",
    imageHint: "pack",
  },
  {
    name: "Superior 45",
    brand: "Gossamer Gear",
    category: "pack" as const,
    weightGrams: 765,
    priceUsd: 255,
    capacityLiters: 45,
    durability: 7,
    comfort: 7,
    skillLevel: "intermediate" as const,
    bestFor: "alpine,mixed,desert",
    description: "Frameless-friendly ultralight pack for refined base weights.",
    imageHint: "pack",
  },
  {
    name: "Windrider 55",
    brand: "Hyperlite Mountain Gear",
    category: "pack" as const,
    weightGrams: 907,
    priceUsd: 359,
    capacityLiters: 55,
    durability: 9,
    comfort: 7,
    skillLevel: "intermediate" as const,
    bestFor: "alpine,coastal,mixed",
    description: "Dyneema pack built for abrasion, weather, and long trail abuse.",
    imageHint: "pack",
  },
  {
    name: "Toaks 750ml Pot",
    brand: "Toaks",
    category: "cook" as const,
    weightGrams: 112,
    priceUsd: 28,
    durability: 8,
    comfort: 6,
    skillLevel: "beginner" as const,
    bestFor: "alpine,forest,desert,coastal,mixed",
    description: "Titanium staple for simple boil-and-eat kitchen kits.",
    imageHint: "cook",
  },
  {
    name: "PocketRocket 2",
    brand: "MSR",
    category: "cook" as const,
    weightGrams: 73,
    priceUsd: 50,
    durability: 9,
    comfort: 7,
    skillLevel: "beginner" as const,
    bestFor: "alpine,forest,desert,mixed",
    description: "Compact canister stove with reliable simmer and packability.",
    imageHint: "stove",
  },
  {
    name: "BeFree 1.0L",
    brand: "Katadyn",
    category: "water" as const,
    weightGrams: 63,
    priceUsd: 45,
    capacityLiters: 1,
    durability: 6,
    comfort: 8,
    skillLevel: "beginner" as const,
    bestFor: "forest,alpine,mixed",
    description: "Fast-flow soft flask filter ideal for frequent water sources.",
    imageHint: "filter",
  },
  {
    name: "Sawyer Squeeze",
    brand: "Sawyer",
    category: "water" as const,
    weightGrams: 85,
    priceUsd: 39,
    durability: 8,
    comfort: 7,
    skillLevel: "beginner" as const,
    bestFor: "desert,forest,mixed,coastal",
    description: "Proven hollow-fiber filter with flexible bottle compatibility.",
    imageHint: "filter",
  },
  {
    name: "Alpha Fleece Hoody",
    brand: "Senchi Designs",
    category: "clothing" as const,
    weightGrams: 148,
    priceUsd: 95,
    durability: 7,
    comfort: 9,
    skillLevel: "intermediate" as const,
    bestFor: "alpine,forest,mixed",
    description: "High-loft active insulation that shines on cool climbs.",
    imageHint: "fleece",
  },
  {
    name: "Torrentshell 3L",
    brand: "Patagonia",
    category: "clothing" as const,
    weightGrams: 343,
    priceUsd: 179,
    waterproofRating: "3L H2No",
    durability: 8,
    comfort: 8,
    skillLevel: "beginner" as const,
    bestFor: "forest,coastal,mixed",
    description: "Durable rain shell for wet forest and coastal systems.",
    imageHint: "rain-shell",
  },
  {
    name: "Ghost Whisperer 2",
    brand: "Mountain Hardwear",
    category: "clothing" as const,
    weightGrams: 207,
    priceUsd: 300,
    durability: 6,
    comfort: 9,
    skillLevel: "intermediate" as const,
    bestFor: "alpine,mixed",
    description: "Ultralight down puffy for camp and summit pushes.",
    imageHint: "puffy",
  },
  {
    name: "Speedgoat 6",
    brand: "Hoka",
    category: "footwear" as const,
    weightGrams: 624,
    priceUsd: 155,
    durability: 7,
    comfort: 9,
    skillLevel: "beginner" as const,
    bestFor: "forest,mixed,alpine",
    description: "Max-cushion trail shoe for long rocky approaches.",
    imageHint: "shoes",
  },
  {
    name: "Lone Peak 8",
    brand: "Altra",
    category: "footwear" as const,
    weightGrams: 596,
    priceUsd: 150,
    durability: 7,
    comfort: 8,
    skillLevel: "beginner" as const,
    bestFor: "desert,forest,mixed",
    description: "Zero-drop trail shoe with roomy toe box for big mile days.",
    imageHint: "shoes",
  },
  {
    name: "inReach Mini 2",
    brand: "Garmin",
    category: "electronics" as const,
    weightGrams: 100,
    priceUsd: 400,
    durability: 9,
    comfort: 8,
    skillLevel: "beginner" as const,
    bestFor: "alpine,desert,coastal,mixed,forest",
    description: "Satellite messenger for off-grid check-ins and SOS.",
    imageHint: "gps",
  },
  {
    name: "Microspikes",
    brand: "Kahtoola",
    category: "safety" as const,
    weightGrams: 340,
    priceUsd: 75,
    durability: 9,
    comfort: 7,
    skillLevel: "beginner" as const,
    bestFor: "alpine",
    description: "Essential traction for early-season snow and icy cols.",
    imageHint: "traction",
  },
  {
    name: "Carbon Cork Z-Poles",
    brand: "Black Diamond",
    category: "navigation" as const,
    weightGrams: 450,
    priceUsd: 200,
    durability: 8,
    comfort: 9,
    skillLevel: "beginner" as const,
    bestFor: "alpine,forest,mixed",
    description: "Foldable trekking poles that double as shelter supports.",
    imageHint: "poles",
  },
];

const starterPack = [
  {
    name: "Exos 48",
    brand: "Osprey",
    category: "pack" as const,
    weightGrams: 1190,
    priceUsd: 240,
    quantity: 1,
    worn: false,
    consumable: false,
    packed: true,
    notes: "Primary pack",
  },
  {
    name: "NeoAir XLite NXT",
    brand: "Therm-a-Rest",
    category: "sleep" as const,
    weightGrams: 371,
    priceUsd: 210,
    quantity: 1,
    worn: false,
    consumable: false,
    packed: true,
    notes: "",
  },
  {
    name: "Alpha Fleece Hoody",
    brand: "Senchi Designs",
    category: "clothing" as const,
    weightGrams: 148,
    priceUsd: 95,
    quantity: 1,
    worn: true,
    consumable: false,
    packed: true,
    notes: "Worn while hiking",
  },
  {
    name: "BeFree 1.0L",
    brand: "Katadyn",
    category: "water" as const,
    weightGrams: 63,
    priceUsd: 45,
    quantity: 1,
    worn: false,
    consumable: false,
    packed: true,
    notes: "",
  },
  {
    name: "Fuel canister",
    brand: "Generic",
    category: "cook" as const,
    weightGrams: 200,
    priceUsd: 8,
    quantity: 1,
    worn: false,
    consumable: true,
    packed: true,
    notes: "100g iso-butane",
  },
];

export async function seedIfEmpty() {
  const [{ value: trailCount }] = await db.select({ value: count() }).from(trails);
  if (trailCount === 0) {
    await db.insert(trails).values(trailSeed);
  }

  const [{ value: catalogCount }] = await db
    .select({ value: count() })
    .from(catalogItems);
  if (catalogCount === 0) {
    await db.insert(catalogItems).values(catalogSeed);
  }

  const [{ value: gearCount }] = await db.select({ value: count() }).from(userGear);
  if (gearCount === 0) {
    await db.insert(userGear).values(
      starterPack.map((item) => ({
        ...item,
        createdAt: new Date().toISOString(),
      })),
    );
  }
}
